/*

QUESTÃO 01 - JÁ SABE ORGANIZAR SUAS PASTAS COM VS CODE ?
-> SIM

QUESTÃO 02 - NODE.JS ESTÁ INSTALADO NO SEU COMPUTADOR ?
-> SIM

QUESTÃO 03 - SABE DIFERENCIAR HTML5, CSS3 E JS DENTRO DE UM CÓDIGO ?
-> SIM

QUESTÃO 04 - SABE DISPARAR ALERTAS, CONFIRMAÇÔES E PERGUNTAS ?
-> SIM


REGRAS DE IDENTIFICADORES (VARIÁVEIS) EM JAVASCRIPT :

1 - PODEM COMEÇAR COM (LETRA, $ OU _);

2 - NÃO PODEM COMEÇAR COM NÚMEROS;

3 - É POSSÍVEL USAR (LETRAS OU NÚMEROS);

4 - É POSSÍVEL USAR (ACENTOS E SÍMBOLOS);
 
5 - NÃO PODEM CONTER (ESPAÇOS);

6 - NÃO PODEM SER (PALAVRAS RESERVADAS);

7 -  (MAÍUSCULAS E MINÚSCULAS) FAZEM A DIFERENÇA;

8 - TENTE ESCOLHER (NOMES COERENTES) PARA AS VARIÁVEIS;

9 - EVITE SE TORNAR UM (PROGRAMADOR ALFABETO) OU UM (PROGRAMADOR CONTADOR);


  $  (DATA TYPES) EM JAVASCRIPT $

* VARIÁVEIS SERVEM PRA GUARDAR TIPOS DE DADOS;

* NÚMEROS INTEIROS(NÃO FRACIONÁRIOS) E NÚMEROS FRACIONÁRIOS(FLOATS) EM JAVASCRIPT, SÃO DO MESMO TIPO (NUMBER)

- VALORES INTERNOS DO TIPO (NUMBER);
    - INFINITY
    - NaN()

* STRINGS SÃO CADEIAS DE CARACTERES 

* TRUE E FALSE SÃO VALORES (BOOLEAN)

* NULL (NULO)

* UNDEFINED (NÃO DEFINIDO)

* OBJECT (OBJETO)

    ARRAY (VALOR INTERNO)

* FUNCTION (FUNÇÃO DO TIPO PRIMITIVO)

* TYPE OF - EXIBE OS TIPOS DE DADOS 


 */

//usando o typeof para mostrar os tipos de dados primitivos pelo ID do h1
document.getElementById('mostrar').innerText = typeof([]);

//mostrando os tipos usando alert
alert(typeof(""));

